ALTER TABLE CASH DROP FOREIGN KEY FK_CASH_ACCOUNT_ID
ALTER TABLE holdings DROP FOREIGN KEY FK_holdings_ACCOUNT_ID
ALTER TABLE holdings DROP FOREIGN KEY FK_holdings_STOCK_ID
ALTER TABLE transactions DROP FOREIGN KEY FK_transactions_STOCK_ID
ALTER TABLE transactions DROP FOREIGN KEY FK_transactions_ACCOUNT_ID
DROP TABLE account
DROP TABLE CASH
DROP TABLE holdings
DROP TABLE stocks
DROP TABLE transactions
